FROM ansibleplaybookbundle/apb-base

LABEL "com.redhat.apb.spec"=\
"dmVyc2lvbjogMS4wCm5hbWU6IG1jcy1zZXJ2ZXItYXBiCmRlc2NyaXB0aW9uOiBBZXJvR2VhciBt\
Y3Mtc2VydmVyIFNlcnZlciAKYmluZGFibGU6IFRydWUKYXN5bmM6IG9wdGlvbmFsCm1ldGFkYXRh\
OgogIGRpc3BsYXlOYW1lOiBNb2JpbGUgQ2xpZW50IFNlcnZpY2UgMTIKICBsb25nRGVzY3JpcHRp\
b246ICJBbiBBUEIgZGVwbG95aW5nIHRoZSBBZXJvR2VhciBtY3Mtc2VydmVyIFNlcnZlciB3aXRo\
IHBlcnNpc3RlbnQgc3RvcmFnZSBhbmQgYXV0aGVudGljYXRpb24gdGhyb3VnaCBPcGVuc2hpZnQi\
CiAgaW1hZ2VVcmw6ICJodHRwczovL3Bicy50d2ltZy5jb20vcHJvZmlsZV9pbWFnZXMvMTc5NDQ0\
MDAwNS9hZXJvZ2Vhcl9pY29uLTFfNDAweDQwMC5wbmciCiAgZG9jdW1lbnRhdGlvblVybDogImh0\
dHBzOi8vZG9jcy5hZXJvZ2Vhci5vcmcvZXh0ZXJuYWwvYXBiL21jcy1zZXJ2ZXIuaHRtbCIKICBw\
cm92aWRlckRpc3BsYXlOYW1lOiAiUmVkIEhhdCwgSW5jLiIKICBkZXBlbmRlbmNpZXM6IAogICAg\
ICAtICJkb2NrZXIuaW8vb3BlbnNoaWZ0L29hdXRoLXByb3h5OnYxLjEuMCIKICAgICAgLSAiZG9j\
a2VyLmlvL2Flcm9nZWFyL21vYmlsZS1jbGllbnQtc2VydmljZTpsYXRlc3QiCiAgc2VydmljZU5h\
bWU6IG1jcy1zZXJ2ZXIKICBiaW5kaW5nc0xpbWl0OiAyCnBsYW5zOgogIC0gbmFtZTogZGVmYXVs\
dAogICAgZGVzY3JpcHRpb246IFBlcnNpc3RlbnQgZGVwbG95bWVudCBvZiBtY3Mtc2VydmVyCiAg\
ICBmcmVlOiBUcnVlCiAgICBwYXJhbWV0ZXJzOiBbXQo="


COPY playbooks /opt/apb/actions
COPY roles /opt/ansible/roles
COPY vars /opt/ansible/vars
RUN chmod -R g=u /opt/{ansible,apb}
USER apb