- name: Mobile Developer Console Server deployment
  openshift_v1_deployment_config:
    name: '{{ mobile_developer_console_deploymentconfig_name }}'
    namespace: "{{ namespace }}"
    labels:
      app: mdc-server
      service: mdc-server
      name: mdc-server
      mobile: enabled
    replicas: 1
    selector:
      app: mdc-server
      service: mdc-server
    spec_template_metadata_labels:
      app: mdc-server
      service: mdc-server
    spec_template_spec_service_account_name: '{{ mobile_developer_console_sa_name }}'
    containers:
    - name: mdc-server
      image: '{{ mobile_developer_console_image }}:{{ mobile_developer_console_image_tag }}'
      imagePullPolicy: Always
      env:
      - name: SERVER_PORT
        value: "4000"
      - name: NAMESPACE
        value: '{{ namespace }}'
      - name: ENABLE_BUILD_TAB
        value: '{{ mobile_developer_console_enable_build_tab }}'
      ports:
      - name: mdc-server
        protocol: TCP
        container_port: 4000
    - name: mdc-server-oauth-proxy
      image: '{{ proxy_image }}:{{ proxy_image_tag }}'
      imagePullPolicy: Always
      ports:
      - containerPort: '{{ mobile_developer_console_proxy_port }}'
        name: public
      args:
      - --provider=openshift
      - --openshift-service-account={{ mobile_developer_console_sa_name }}
      - --upstream=http://localhost:{{ mobile_developer_console_port }}/
      - --openshift-sar=[{"namespace":"{{ namespace }}","resource":"secrets","name":"mdc-server","verb":"list"}]
      - --http-address=0.0.0.0:{{ mobile_developer_console_proxy_port }}
      - --https-address=
      - --cookie-secret=SECRET
      - --cookie-httponly=false
    

- name: create mdc-server service
  k8s_v1_service:
    name: '{{ mobile_developer_console_service_name }}'
    namespace: '{{ namespace }}'
    annotations:
      org.aerogear.metrics/plain_endpoint: "/rest/prometheus/metrics"
    labels:
      app: mdc-server
      service: mdc-server
      mobile: enabled
    selector:
      app: mdc-server
      service: mdc-server
    ports:
      - name: web
        port: 80
        target_port: 4000
  register: mobile_developer_console_service

- name: create mdc-server Proxy
  k8s_v1_service:
    name: '{{ mobile_developer_console_proxy_service_name }}'
    namespace: '{{ namespace }}'
    labels:
      app: mdc-server
      service: mdc-server-proxy
    selector:
      app: mdc-server
      service: mdc-server
    ports:
      - name: web
        port: 80
        target_port: '{{ mobile_developer_console_proxy_port }}'

- name: create mdc-server https route
  openshift_v1_route:
    name: '{{ mobile_developer_console_route_name }}'
    namespace: '{{ namespace }}'
    labels:
      app: mdc-server
      service: mdc-server-proxy
    to_name: mdc-server-proxy
    spec_port_target_port: web
    spec_tls_termination: edge
  register: mobile_developer_console_route

# We need to wait for the deployment to be ready before we can exit the ansible job
- name: "Wait for all mdc-server containers to become ready"
  shell: oc get pods --namespace={{ namespace }} --selector="deploymentconfig={{ mobile_developer_console_deploymentconfig_name }}" -o jsonpath='{.items[*].status.containerStatuses[?(@.ready==true)].ready}'| wc -w
  register: mobile_developer_console_result
  until: mobile_developer_console_result.stdout.find("2") != -1
  retries: 30
  delay: 5

# This is currently needed until https://github.com/openshift/ansible-service-broker/issues/847 is resolved
- name: Make the data available to be used in the binding
  asb_encode_binding:
    fields:
      NAMESPACE: "{{ namespace }}"

- name: "Create mdc-server secret yaml file"
  template:
    src: secret.yml.j2
    dest: /tmp/secret.yaml

- name: "Create mdc-server secret"
  shell: "oc create -f /tmp/secret.yaml -n {{ namespace }}"

- name: "Delete mdc-server Secret Template File"
  file: path=/tmp/secret.yaml state=absent
