# MCS Values
mobile_developer_console_image: "docker.io/aerogear/mobile-developer-console"
mobile_developer_console_image_tag: "master"
mobile_developer_console_port: 4000
mobile_developer_console_proxy_port: 4180
mobile_developer_console_enable_build_tab: false
# OAuth Proxy values
proxy_image: "docker.io/openshift/oauth-proxy"
proxy_image_tag: "v1.1.0"
