- name: mobile-client-service deployment
  openshift_v1_deployment_config:
    name: '{{ mobile-client-service_deploymentconfig_name }}'
    namespace: "{{ namespace }}"
    labels:
      app: mobile-client-service
      service: mobile-client-service
      name: mobile-client-service
      mobile: enabled
    replicas: 1
    selector:
      app: mobile-client-service
      service: mobile-client-service
    spec_template_metadata_labels:
      app: mobile-client-service
      service: mobile-client-service
    spec_template_spec_service_account_name: '{{ proxy_serviceaccount_name }}'
    containers:
    - name: mobile-client-service
      image: '{{ mobile-client-service_image }}:{{ mobile-client-service_image_tag }}'
      env:
      - name: SERVER_PORT
        value: "4000"
      - name: SERVER_IMAGE
        value: aerogear/mobile-client-service:latest
      - name: SERVICE_NAME
        value: mobile-client-service
      ports:
      - name: mobile-client-service
        protocol: TCP
        container_port: 4000
    - name: mobile-client-service-oauth-proxy
      image: '{{ proxy_image }}:{{ proxy_image_tag }}'
      imagePullPolicy: IfNotPresent
      ports:
      - containerPort: '{{ mobile-client-service_proxy_port }}'
        name: public
      args:
      - --provider=openshift
      - --openshift-service-account={{ proxy_serviceaccount_name }}
      - --mobile-client-servicetream=http://localhost:{{ mobile-client-service_port }}
      - >-
        --openshift-sar={"namespace":"{{ namespace }}","resource":"deploymentconfigs","name":"mobile-client-service","verb":"update"}
      - --http-address=0.0.0.0:{{ mobile-client-service_proxy_port }}
      - --skip-auth-regex=/rest/sender,/rest/registry/device,/rest/prometheus/metrics
      - --https-address=
      - --cookie-secret=SECRET
    - name: mobile-client-service
      image: '{{ mobile-client-service_sidecar_image }}:{{ mobile-client-service_sidecar_image_tag }}'
      imagePullPolicy: IfNotPresent
      env:
      - name: NAMESPACE
        value: "{{ namespace }}"

- name: create mobile-client-service service
  k8s_v1_service:
    name: '{{ mobile-client-service_service_name }}'
    namespace: '{{ namespace }}'
    annotations:
      org.aerogear.metrics/plain_endpoint: "/rest/prometheus/metrics"
    labels:
      app: mobile-client-service
      service: mobile-client-service
      mobile: enabled
    selector:
      app: mobile-client-service
      service: mobile-client-service
    ports:
      - name: web
        port: 80
        target_port: 4000
  register: mobile-client-service_service

- name: create mobile-client-service Proxy
  k8s_v1_service:
    name: '{{ mobile-client-service_proxy_service_name }}'
    namespace: '{{ namespace }}'
    labels:
      app: mobile-client-service
      service: mobile-client-service-proxy
    selector:
      app: mobile-client-service
      service: mobile-client-service
    ports:
      - name: web
        port: 80
        target_port: '{{ mobile-client-service_proxy_port }}'

- name: create mobile-client-service route
  openshift_v1_route:
    name: '{{ mobile-client-service_route_name }}'
    namespace: '{{ namespace }}'
    labels:
      app: mobile-client-service
      service: mobile-client-service-proxy
    to_name: mobile-client-service-proxy
    spec_port_target_port: web
    spec_tls_termination: edge
  register: mobile-client-service_route

# We need to wait for the deployment to be ready before we can exit the ansible job
- name: "Wait for all mobile-client-service containers to become ready"
  shell: oc get pods --namespace={{ namespace }} --selector="deploymentconfig={{ mobile-client-service_deploymentconfig_name }}" -o jsonpath='{.items[*].status.containerStatuses[?(@.ready==true)].ready}'| wc -w
  register: mobile-client-service_result
  until: mobile-client-service_result.stdout.find("1") != -1
  retries: 30
  delay: 5
