- name: Mobile Client Service Server deployment
  openshift_v1_deployment_config:
    name: '{{ mobile_client_service_deploymentconfig_name }}'
    namespace: "{{ namespace }}"
    labels:
      app: mcs-server
      service: mcs-server
      name: mcs-server
      mobile: enabled
    replicas: 1
    selector:
      app: mcs-server
      service: mcs-server
    spec_template_metadata_labels:
      app: mcs-server
      service: mcs-server
    spec_template_spec_service_account_name: '{{ proxy_serviceaccount_name }}'
    containers:
    - name: mcs-server
      image: '{{ mobile_client_service_image }}:{{ mobile_client_service_image_tag }}'
      env:
      - name: SERVER_PORT
        value: "4000"
      ports:
      - name: mcs-server
        protocol: TCP
        container_port: 4000
    - name: mcs-server-oauth-proxy
      image: '{{ proxy_image }}:{{ proxy_image_tag }}'
      imagePullPolicy: IfNotPresent
      ports:
      - containerPort: '{{ mobile_client_service_proxy_port }}'
        name: public
      args:
      - --provider=openshift
      - --openshift-service-account={{ proxy_serviceaccount_name }}
      - --upstream=http://localhost:{{ mobile_client_service_port }}
      - --openshift-sar={"namespace":"{{ namespace }}","resource":"deploymentconfigs","name":"mcs-server","verb":"update"}
      - --http-address=0.0.0.0:{{ mobile_client_service_proxy_port }}
      - --https-address=
      - --cookie-secret=SECRET
    

- name: create mcs-server service
  k8s_v1_service:
    name: '{{ mobile_client_service_service_name }}'
    namespace: '{{ namespace }}'
    annotations:
      org.aerogear.metrics/plain_endpoint: "/rest/prometheus/metrics"
    labels:
      app: mcs-server
      service: mcs-server
      mobile: enabled
    selector:
      app: mcs-server
      service: mcs-server
    ports:
      - name: web
        port: 80
        target_port: 4000
  register: mobile_client_service_service

- name: create mcs-server Proxy
  k8s_v1_service:
    name: '{{ mobile_client_service_proxy_service_name }}'
    namespace: '{{ namespace }}'
    labels:
      app: mcs-server
      service: mcs-server-proxy
    selector:
      app: mcs-server
      service: mcs-server
    ports:
      - name: web
        port: 80
        target_port: '{{ mobile_client_service_proxy_port }}'

- name: create mcs-server https route
  openshift_v1_route:
    name: '{{ mobile_client_service_route_name }}'
    namespace: '{{ namespace }}'
    labels:
      app: mcs-server
      service: mcs-server-proxy
    to_name: mcs-server-proxy
    spec_port_target_port: web
    spec_tls_termination: edge
  register: mobile_client_service_route

# We need to wait for the deployment to be ready before we can exit the ansible job
- name: "Wait for all mcs-server containers to become ready"
  shell: oc get pods --namespace={{ namespace }} --selector="deploymentconfig={{ mobile_client_service_deploymentconfig_name }}" -o jsonpath='{.items[*].status.containerStatuses[?(@.ready==true)].ready}'| wc -w
  register: mobile_client_service_result
  until: mobile_client_service_result.stdout.find("2") != -1
  retries: 30
  delay: 5

# This is currently needed until https://github.com/openshift/ansible-service-broker/issues/847 is resolved
- name: Make the data available to be used in the binding
  asb_encode_binding:
    fields:
      NAMESPACE: "{{ namespace }}"

- name: "Create mcs-server secret yaml file"
  template:
    src: secret.yml.j2
    dest: /tmp/secret.yaml

- name: "Create mcs-server secret"
  shell: "oc create -f /tmp/secret.yaml -n {{ namespace }}"

- name: "Delete mcs-server Secret Template File"
  file: path=/tmp/secret.yaml state=absent